---
module: info_panel
main: info_panel/main.py
libs:
  - aio.py
  - chronos.py
  - colors
  - led_matrix.py
  - my_wifi.py
requirements:
  - adafruit_bitmap_font
  - adafruit_datetime.mpy
  - adafruit_display_text
  - adafruit_fakerequests.mpy
  - adafruit_io
  - adafruit_matrixportal
  - adafruit_minimqtt
  - adafruit_ntp.mpy
  - adafruit_portalbase
  - adafruit_requests.mpy
  - neopixel.mpy
  # - CircuitPython_Community_Bundle/ifttt.mpy
