---
package: boids
entry_point: boids/main.py
libs:
  - chronos.py
  - colors
  - led_matrix.py
  - my_wifi.py
ignore:
  - README.md
requirements:
  - adafruit_connection_manager.mpy
  - adafruit_datetime.mpy
  - adafruit_matrixportal
  - adafruit_ntp.mpy
  - adafruit_portalbase
  - adafruit_requests.mpy
  - neopixel.mpy
