---
module: playground
main: playground/main.py
libs:
  - led_matrix.py
requirements:
  - adafruit_bitmap_font
  - adafruit_datetime.mpy
  - adafruit_display_text
  - adafruit_fakerequests.mpy
  - adafruit_io
  - adafruit_matrixportal
  - adafruit_minimqtt
  - adafruit_ntp.mpy
  - adafruit_portalbase
  - adafruit_requests.mpy
  - neopixel.mpy
